// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chatbot.proto

package chatbotpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ChatAppType - chat app type
type ChatAppType int32

const (
	ChatAppType_CAT_TELEGRAM ChatAppType = 0
	ChatAppType_CAT_COOLQ    ChatAppType = 1
)

var ChatAppType_name = map[int32]string{
	0: "CAT_TELEGRAM",
	1: "CAT_COOLQ",
}
var ChatAppType_value = map[string]int32{
	"CAT_TELEGRAM": 0,
	"CAT_COOLQ":    1,
}

func (x ChatAppType) String() string {
	return proto.EnumName(ChatAppType_name, int32(x))
}
func (ChatAppType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_chatbot_b4ae99ab1bd86481, []int{0}
}

// UserAppInfo - user app info
type UserAppInfo struct {
	App                  ChatAppType `protobuf:"varint,1,opt,name=app,proto3,enum=chatbotpb.ChatAppType" json:"app,omitempty"`
	Appuid               string      `protobuf:"bytes,2,opt,name=appuid,proto3" json:"appuid,omitempty"`
	Appuname             string      `protobuf:"bytes,3,opt,name=appuname,proto3" json:"appuname,omitempty"`
	Chatnums             int32       `protobuf:"varint,4,opt,name=chatnums,proto3" json:"chatnums,omitempty"`
	UsernameAppServ      string      `protobuf:"bytes,5,opt,name=usernameAppServ,proto3" json:"usernameAppServ,omitempty"`
	Lang                 string      `protobuf:"bytes,6,opt,name=lang,proto3" json:"lang,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserAppInfo) Reset()         { *m = UserAppInfo{} }
func (m *UserAppInfo) String() string { return proto.CompactTextString(m) }
func (*UserAppInfo) ProtoMessage()    {}
func (*UserAppInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_chatbot_b4ae99ab1bd86481, []int{0}
}
func (m *UserAppInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAppInfo.Unmarshal(m, b)
}
func (m *UserAppInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAppInfo.Marshal(b, m, deterministic)
}
func (dst *UserAppInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAppInfo.Merge(dst, src)
}
func (m *UserAppInfo) XXX_Size() int {
	return xxx_messageInfo_UserAppInfo.Size(m)
}
func (m *UserAppInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAppInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserAppInfo proto.InternalMessageInfo

func (m *UserAppInfo) GetApp() ChatAppType {
	if m != nil {
		return m.App
	}
	return ChatAppType_CAT_TELEGRAM
}

func (m *UserAppInfo) GetAppuid() string {
	if m != nil {
		return m.Appuid
	}
	return ""
}

func (m *UserAppInfo) GetAppuname() string {
	if m != nil {
		return m.Appuname
	}
	return ""
}

func (m *UserAppInfo) GetChatnums() int32 {
	if m != nil {
		return m.Chatnums
	}
	return 0
}

func (m *UserAppInfo) GetUsernameAppServ() string {
	if m != nil {
		return m.UsernameAppServ
	}
	return ""
}

func (m *UserAppInfo) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

// UserInfo - user info
type UserInfo struct {
	Uid                  int64          `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Apps                 []*UserAppInfo `protobuf:"bytes,3,rep,name=apps,proto3" json:"apps,omitempty"`
	Tags                 []string       `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Language             string         `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	Money                int64          `protobuf:"varint,10,opt,name=money,proto3" json:"money,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_chatbot_b4ae99ab1bd86481, []int{1}
}
func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (dst *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(dst, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetApps() []*UserAppInfo {
	if m != nil {
		return m.Apps
	}
	return nil
}

func (m *UserInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *UserInfo) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *UserInfo) GetMoney() int64 {
	if m != nil {
		return m.Money
	}
	return 0
}

// AppGroupInfo - app group info
type AppGroupInfo struct {
	App                  ChatAppType `protobuf:"varint,1,opt,name=app,proto3,enum=chatbotpb.ChatAppType" json:"app,omitempty"`
	UsernameAppServ      string      `protobuf:"bytes,2,opt,name=usernameAppServ,proto3" json:"usernameAppServ,omitempty"`
	Groupid              string      `protobuf:"bytes,3,opt,name=groupid,proto3" json:"groupid,omitempty"`
	Groupname            string      `protobuf:"bytes,4,opt,name=groupname,proto3" json:"groupname,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AppGroupInfo) Reset()         { *m = AppGroupInfo{} }
func (m *AppGroupInfo) String() string { return proto.CompactTextString(m) }
func (*AppGroupInfo) ProtoMessage()    {}
func (*AppGroupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_chatbot_b4ae99ab1bd86481, []int{2}
}
func (m *AppGroupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppGroupInfo.Unmarshal(m, b)
}
func (m *AppGroupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppGroupInfo.Marshal(b, m, deterministic)
}
func (dst *AppGroupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppGroupInfo.Merge(dst, src)
}
func (m *AppGroupInfo) XXX_Size() int {
	return xxx_messageInfo_AppGroupInfo.Size(m)
}
func (m *AppGroupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AppGroupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AppGroupInfo proto.InternalMessageInfo

func (m *AppGroupInfo) GetApp() ChatAppType {
	if m != nil {
		return m.App
	}
	return ChatAppType_CAT_TELEGRAM
}

func (m *AppGroupInfo) GetUsernameAppServ() string {
	if m != nil {
		return m.UsernameAppServ
	}
	return ""
}

func (m *AppGroupInfo) GetGroupid() string {
	if m != nil {
		return m.Groupid
	}
	return ""
}

func (m *AppGroupInfo) GetGroupname() string {
	if m != nil {
		return m.Groupname
	}
	return ""
}

// AppServInfo - app server info
type AppServInfo struct {
	Token                string      `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AppType              ChatAppType `protobuf:"varint,2,opt,name=appType,proto3,enum=chatbotpb.ChatAppType" json:"appType,omitempty"`
	Username             string      `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Sessionid            string      `protobuf:"bytes,4,opt,name=sessionid,proto3" json:"sessionid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AppServInfo) Reset()         { *m = AppServInfo{} }
func (m *AppServInfo) String() string { return proto.CompactTextString(m) }
func (*AppServInfo) ProtoMessage()    {}
func (*AppServInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_chatbot_b4ae99ab1bd86481, []int{3}
}
func (m *AppServInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppServInfo.Unmarshal(m, b)
}
func (m *AppServInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppServInfo.Marshal(b, m, deterministic)
}
func (dst *AppServInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppServInfo.Merge(dst, src)
}
func (m *AppServInfo) XXX_Size() int {
	return xxx_messageInfo_AppServInfo.Size(m)
}
func (m *AppServInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AppServInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AppServInfo proto.InternalMessageInfo

func (m *AppServInfo) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AppServInfo) GetAppType() ChatAppType {
	if m != nil {
		return m.AppType
	}
	return ChatAppType_CAT_TELEGRAM
}

func (m *AppServInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AppServInfo) GetSessionid() string {
	if m != nil {
		return m.Sessionid
	}
	return ""
}

// RegisterAppService - register app service
type RegisterAppService struct {
	AppServ              *AppServInfo `protobuf:"bytes,1,opt,name=appServ,proto3" json:"appServ,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegisterAppService) Reset()         { *m = RegisterAppService{} }
func (m *RegisterAppService) String() string { return proto.CompactTextString(m) }
func (*RegisterAppService) ProtoMessage()    {}
func (*RegisterAppService) Descriptor() ([]byte, []int) {
	return fileDescriptor_chatbot_b4ae99ab1bd86481, []int{4}
}
func (m *RegisterAppService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAppService.Unmarshal(m, b)
}
func (m *RegisterAppService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAppService.Marshal(b, m, deterministic)
}
func (dst *RegisterAppService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAppService.Merge(dst, src)
}
func (m *RegisterAppService) XXX_Size() int {
	return xxx_messageInfo_RegisterAppService.Size(m)
}
func (m *RegisterAppService) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAppService.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAppService proto.InternalMessageInfo

func (m *RegisterAppService) GetAppServ() *AppServInfo {
	if m != nil {
		return m.AppServ
	}
	return nil
}

// ReplyRegisterAppService - reply RegisterAppService
type ReplyRegisterAppService struct {
	AppType              ChatAppType `protobuf:"varint,1,opt,name=appType,proto3,enum=chatbotpb.ChatAppType" json:"appType,omitempty"`
	Error                string      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	SessionID            string      `protobuf:"bytes,3,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReplyRegisterAppService) Reset()         { *m = ReplyRegisterAppService{} }
func (m *ReplyRegisterAppService) String() string { return proto.CompactTextString(m) }
func (*ReplyRegisterAppService) ProtoMessage()    {}
func (*ReplyRegisterAppService) Descriptor() ([]byte, []int) {
	return fileDescriptor_chatbot_b4ae99ab1bd86481, []int{5}
}
func (m *ReplyRegisterAppService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyRegisterAppService.Unmarshal(m, b)
}
func (m *ReplyRegisterAppService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyRegisterAppService.Marshal(b, m, deterministic)
}
func (dst *ReplyRegisterAppService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyRegisterAppService.Merge(dst, src)
}
func (m *ReplyRegisterAppService) XXX_Size() int {
	return xxx_messageInfo_ReplyRegisterAppService.Size(m)
}
func (m *ReplyRegisterAppService) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyRegisterAppService.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyRegisterAppService proto.InternalMessageInfo

func (m *ReplyRegisterAppService) GetAppType() ChatAppType {
	if m != nil {
		return m.AppType
	}
	return ChatAppType_CAT_TELEGRAM
}

func (m *ReplyRegisterAppService) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ReplyRegisterAppService) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

// FileData - file data
type FileData struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	FileData             []byte   `protobuf:"bytes,2,opt,name=fileData,proto3" json:"fileData,omitempty"`
	FileType             string   `protobuf:"bytes,3,opt,name=fileType,proto3" json:"fileType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileData) Reset()         { *m = FileData{} }
func (m *FileData) String() string { return proto.CompactTextString(m) }
func (*FileData) ProtoMessage()    {}
func (*FileData) Descriptor() ([]byte, []int) {
	return fileDescriptor_chatbot_b4ae99ab1bd86481, []int{6}
}
func (m *FileData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileData.Unmarshal(m, b)
}
func (m *FileData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileData.Marshal(b, m, deterministic)
}
func (dst *FileData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileData.Merge(dst, src)
}
func (m *FileData) XXX_Size() int {
	return xxx_messageInfo_FileData.Size(m)
}
func (m *FileData) XXX_DiscardUnknown() {
	xxx_messageInfo_FileData.DiscardUnknown(m)
}

var xxx_messageInfo_FileData proto.InternalMessageInfo

func (m *FileData) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *FileData) GetFileData() []byte {
	if m != nil {
		return m.FileData
	}
	return nil
}

func (m *FileData) GetFileType() string {
	if m != nil {
		return m.FileType
	}
	return ""
}

// ChatMsg - chat message
type ChatMsg struct {
	Msg                  string        `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Uai                  *UserAppInfo  `protobuf:"bytes,2,opt,name=uai,proto3" json:"uai,omitempty"`
	Agi                  *AppGroupInfo `protobuf:"bytes,3,opt,name=agi,proto3" json:"agi,omitempty"`
	Filename             string        `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"` // Deprecated: Do not use.
	FileData             []byte        `protobuf:"bytes,5,opt,name=fileData,proto3" json:"fileData,omitempty"` // Deprecated: Do not use.
	Error                string        `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	Token                string        `protobuf:"bytes,7,opt,name=token,proto3" json:"token,omitempty"`
	SessionID            string        `protobuf:"bytes,8,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	FileType             string        `protobuf:"bytes,9,opt,name=fileType,proto3" json:"fileType,omitempty"` // Deprecated: Do not use.
	File                 *FileData     `protobuf:"bytes,10,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ChatMsg) Reset()         { *m = ChatMsg{} }
func (m *ChatMsg) String() string { return proto.CompactTextString(m) }
func (*ChatMsg) ProtoMessage()    {}
func (*ChatMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_chatbot_b4ae99ab1bd86481, []int{7}
}
func (m *ChatMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMsg.Unmarshal(m, b)
}
func (m *ChatMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMsg.Marshal(b, m, deterministic)
}
func (dst *ChatMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMsg.Merge(dst, src)
}
func (m *ChatMsg) XXX_Size() int {
	return xxx_messageInfo_ChatMsg.Size(m)
}
func (m *ChatMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMsg proto.InternalMessageInfo

func (m *ChatMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ChatMsg) GetUai() *UserAppInfo {
	if m != nil {
		return m.Uai
	}
	return nil
}

func (m *ChatMsg) GetAgi() *AppGroupInfo {
	if m != nil {
		return m.Agi
	}
	return nil
}

// Deprecated: Do not use.
func (m *ChatMsg) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

// Deprecated: Do not use.
func (m *ChatMsg) GetFileData() []byte {
	if m != nil {
		return m.FileData
	}
	return nil
}

func (m *ChatMsg) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ChatMsg) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ChatMsg) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

// Deprecated: Do not use.
func (m *ChatMsg) GetFileType() string {
	if m != nil {
		return m.FileType
	}
	return ""
}

func (m *ChatMsg) GetFile() *FileData {
	if m != nil {
		return m.File
	}
	return nil
}

// ChatMsgStream - chat message stream
type ChatMsgStream struct {
	// totalLength - If the message is too long, it will send data in multiple msg, this is the total length.
	TotalLength int32 `protobuf:"varint,1,opt,name=totalLength,proto3" json:"totalLength,omitempty"`
	// curStart - The starting point of the current data (in bytes).
	CurStart int32 `protobuf:"varint,2,opt,name=curStart,proto3" json:"curStart,omitempty"`
	// curLength - The length of the current data (in bytes).
	CurLength int32 `protobuf:"varint,3,opt,name=curLength,proto3" json:"curLength,omitempty"`
	// hashData - This is the hash of each paragraph.
	HashData string `protobuf:"bytes,4,opt,name=hashData,proto3" json:"hashData,omitempty"`
	// totalHashData - If multiple messages return data, this is the hash value of all data, only sent in the last message.
	TotalHashData string `protobuf:"bytes,5,opt,name=totalHashData,proto3" json:"totalHashData,omitempty"`
	// data
	Data []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	// error
	Error string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	// token
	Token string `protobuf:"bytes,8,opt,name=token,proto3" json:"token,omitempty"`
	// sessionID
	SessionID            string   `protobuf:"bytes,9,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	Chat                 *ChatMsg `protobuf:"bytes,10,opt,name=chat,proto3" json:"chat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatMsgStream) Reset()         { *m = ChatMsgStream{} }
func (m *ChatMsgStream) String() string { return proto.CompactTextString(m) }
func (*ChatMsgStream) ProtoMessage()    {}
func (*ChatMsgStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_chatbot_b4ae99ab1bd86481, []int{8}
}
func (m *ChatMsgStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMsgStream.Unmarshal(m, b)
}
func (m *ChatMsgStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMsgStream.Marshal(b, m, deterministic)
}
func (dst *ChatMsgStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMsgStream.Merge(dst, src)
}
func (m *ChatMsgStream) XXX_Size() int {
	return xxx_messageInfo_ChatMsgStream.Size(m)
}
func (m *ChatMsgStream) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMsgStream.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMsgStream proto.InternalMessageInfo

func (m *ChatMsgStream) GetTotalLength() int32 {
	if m != nil {
		return m.TotalLength
	}
	return 0
}

func (m *ChatMsgStream) GetCurStart() int32 {
	if m != nil {
		return m.CurStart
	}
	return 0
}

func (m *ChatMsgStream) GetCurLength() int32 {
	if m != nil {
		return m.CurLength
	}
	return 0
}

func (m *ChatMsgStream) GetHashData() string {
	if m != nil {
		return m.HashData
	}
	return ""
}

func (m *ChatMsgStream) GetTotalHashData() string {
	if m != nil {
		return m.TotalHashData
	}
	return ""
}

func (m *ChatMsgStream) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ChatMsgStream) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ChatMsgStream) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ChatMsgStream) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *ChatMsgStream) GetChat() *ChatMsg {
	if m != nil {
		return m.Chat
	}
	return nil
}

// RequestChatData - request chat data
type RequestChatData struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	SessionID            string   `protobuf:"bytes,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestChatData) Reset()         { *m = RequestChatData{} }
func (m *RequestChatData) String() string { return proto.CompactTextString(m) }
func (*RequestChatData) ProtoMessage()    {}
func (*RequestChatData) Descriptor() ([]byte, []int) {
	return fileDescriptor_chatbot_b4ae99ab1bd86481, []int{9}
}
func (m *RequestChatData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestChatData.Unmarshal(m, b)
}
func (m *RequestChatData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestChatData.Marshal(b, m, deterministic)
}
func (dst *RequestChatData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestChatData.Merge(dst, src)
}
func (m *RequestChatData) XXX_Size() int {
	return xxx_messageInfo_RequestChatData.Size(m)
}
func (m *RequestChatData) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestChatData.DiscardUnknown(m)
}

var xxx_messageInfo_RequestChatData proto.InternalMessageInfo

func (m *RequestChatData) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RequestChatData) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

// ChatBotServInfo - ChatBot service infomation
type ChatBotServInfo struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	SessionID            string   `protobuf:"bytes,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	ServName             string   `protobuf:"bytes,3,opt,name=servName,proto3" json:"servName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatBotServInfo) Reset()         { *m = ChatBotServInfo{} }
func (m *ChatBotServInfo) String() string { return proto.CompactTextString(m) }
func (*ChatBotServInfo) ProtoMessage()    {}
func (*ChatBotServInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_chatbot_b4ae99ab1bd86481, []int{10}
}
func (m *ChatBotServInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatBotServInfo.Unmarshal(m, b)
}
func (m *ChatBotServInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatBotServInfo.Marshal(b, m, deterministic)
}
func (dst *ChatBotServInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatBotServInfo.Merge(dst, src)
}
func (m *ChatBotServInfo) XXX_Size() int {
	return xxx_messageInfo_ChatBotServInfo.Size(m)
}
func (m *ChatBotServInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatBotServInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChatBotServInfo proto.InternalMessageInfo

func (m *ChatBotServInfo) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ChatBotServInfo) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *ChatBotServInfo) GetServName() string {
	if m != nil {
		return m.ServName
	}
	return ""
}

// RegisterChatBotServ - register chatbot service
type RegisterChatBotServ struct {
	ServInfo             *ChatBotServInfo `protobuf:"bytes,1,opt,name=servInfo,proto3" json:"servInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RegisterChatBotServ) Reset()         { *m = RegisterChatBotServ{} }
func (m *RegisterChatBotServ) String() string { return proto.CompactTextString(m) }
func (*RegisterChatBotServ) ProtoMessage()    {}
func (*RegisterChatBotServ) Descriptor() ([]byte, []int) {
	return fileDescriptor_chatbot_b4ae99ab1bd86481, []int{11}
}
func (m *RegisterChatBotServ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterChatBotServ.Unmarshal(m, b)
}
func (m *RegisterChatBotServ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterChatBotServ.Marshal(b, m, deterministic)
}
func (dst *RegisterChatBotServ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterChatBotServ.Merge(dst, src)
}
func (m *RegisterChatBotServ) XXX_Size() int {
	return xxx_messageInfo_RegisterChatBotServ.Size(m)
}
func (m *RegisterChatBotServ) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterChatBotServ.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterChatBotServ proto.InternalMessageInfo

func (m *RegisterChatBotServ) GetServInfo() *ChatBotServInfo {
	if m != nil {
		return m.ServInfo
	}
	return nil
}

// ReplyRegisterChatBotServ - reply RegisterChatBotServ
type ReplyRegisterChatBotServ struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	SessionID            string   `protobuf:"bytes,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyRegisterChatBotServ) Reset()         { *m = ReplyRegisterChatBotServ{} }
func (m *ReplyRegisterChatBotServ) String() string { return proto.CompactTextString(m) }
func (*ReplyRegisterChatBotServ) ProtoMessage()    {}
func (*ReplyRegisterChatBotServ) Descriptor() ([]byte, []int) {
	return fileDescriptor_chatbot_b4ae99ab1bd86481, []int{12}
}
func (m *ReplyRegisterChatBotServ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyRegisterChatBotServ.Unmarshal(m, b)
}
func (m *ReplyRegisterChatBotServ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyRegisterChatBotServ.Marshal(b, m, deterministic)
}
func (dst *ReplyRegisterChatBotServ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyRegisterChatBotServ.Merge(dst, src)
}
func (m *ReplyRegisterChatBotServ) XXX_Size() int {
	return xxx_messageInfo_ReplyRegisterChatBotServ.Size(m)
}
func (m *ReplyRegisterChatBotServ) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyRegisterChatBotServ.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyRegisterChatBotServ proto.InternalMessageInfo

func (m *ReplyRegisterChatBotServ) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ReplyRegisterChatBotServ) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *ReplyRegisterChatBotServ) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*UserAppInfo)(nil), "chatbotpb.UserAppInfo")
	proto.RegisterType((*UserInfo)(nil), "chatbotpb.UserInfo")
	proto.RegisterType((*AppGroupInfo)(nil), "chatbotpb.AppGroupInfo")
	proto.RegisterType((*AppServInfo)(nil), "chatbotpb.AppServInfo")
	proto.RegisterType((*RegisterAppService)(nil), "chatbotpb.RegisterAppService")
	proto.RegisterType((*ReplyRegisterAppService)(nil), "chatbotpb.ReplyRegisterAppService")
	proto.RegisterType((*FileData)(nil), "chatbotpb.FileData")
	proto.RegisterType((*ChatMsg)(nil), "chatbotpb.ChatMsg")
	proto.RegisterType((*ChatMsgStream)(nil), "chatbotpb.ChatMsgStream")
	proto.RegisterType((*RequestChatData)(nil), "chatbotpb.RequestChatData")
	proto.RegisterType((*ChatBotServInfo)(nil), "chatbotpb.ChatBotServInfo")
	proto.RegisterType((*RegisterChatBotServ)(nil), "chatbotpb.RegisterChatBotServ")
	proto.RegisterType((*ReplyRegisterChatBotServ)(nil), "chatbotpb.ReplyRegisterChatBotServ")
	proto.RegisterEnum("chatbotpb.ChatAppType", ChatAppType_name, ChatAppType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatBotServiceClient is the client API for ChatBotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatBotServiceClient interface {
	// registerAppService - register app service
	RegisterAppService(ctx context.Context, in *RegisterAppService, opts ...grpc.CallOption) (*ReplyRegisterAppService, error)
	// sendChat - send chat
	SendChat(ctx context.Context, opts ...grpc.CallOption) (ChatBotService_SendChatClient, error)
	// requestChat - request chat
	RequestChat(ctx context.Context, in *RequestChatData, opts ...grpc.CallOption) (ChatBotService_RequestChatClient, error)
}

type chatBotServiceClient struct {
	cc *grpc.ClientConn
}

func NewChatBotServiceClient(cc *grpc.ClientConn) ChatBotServiceClient {
	return &chatBotServiceClient{cc}
}

func (c *chatBotServiceClient) RegisterAppService(ctx context.Context, in *RegisterAppService, opts ...grpc.CallOption) (*ReplyRegisterAppService, error) {
	out := new(ReplyRegisterAppService)
	err := c.cc.Invoke(ctx, "/chatbotpb.ChatBotService/registerAppService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatBotServiceClient) SendChat(ctx context.Context, opts ...grpc.CallOption) (ChatBotService_SendChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChatBotService_serviceDesc.Streams[0], "/chatbotpb.ChatBotService/sendChat", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatBotServiceSendChatClient{stream}
	return x, nil
}

type ChatBotService_SendChatClient interface {
	Send(*ChatMsgStream) error
	Recv() (*ChatMsgStream, error)
	grpc.ClientStream
}

type chatBotServiceSendChatClient struct {
	grpc.ClientStream
}

func (x *chatBotServiceSendChatClient) Send(m *ChatMsgStream) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatBotServiceSendChatClient) Recv() (*ChatMsgStream, error) {
	m := new(ChatMsgStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatBotServiceClient) RequestChat(ctx context.Context, in *RequestChatData, opts ...grpc.CallOption) (ChatBotService_RequestChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChatBotService_serviceDesc.Streams[1], "/chatbotpb.ChatBotService/requestChat", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatBotServiceRequestChatClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatBotService_RequestChatClient interface {
	Recv() (*ChatMsgStream, error)
	grpc.ClientStream
}

type chatBotServiceRequestChatClient struct {
	grpc.ClientStream
}

func (x *chatBotServiceRequestChatClient) Recv() (*ChatMsgStream, error) {
	m := new(ChatMsgStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatBotServiceServer is the server API for ChatBotService service.
type ChatBotServiceServer interface {
	// registerAppService - register app service
	RegisterAppService(context.Context, *RegisterAppService) (*ReplyRegisterAppService, error)
	// sendChat - send chat
	SendChat(ChatBotService_SendChatServer) error
	// requestChat - request chat
	RequestChat(*RequestChatData, ChatBotService_RequestChatServer) error
}

func RegisterChatBotServiceServer(s *grpc.Server, srv ChatBotServiceServer) {
	s.RegisterService(&_ChatBotService_serviceDesc, srv)
}

func _ChatBotService_RegisterAppService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAppService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatBotServiceServer).RegisterAppService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatbotpb.ChatBotService/RegisterAppService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatBotServiceServer).RegisterAppService(ctx, req.(*RegisterAppService))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatBotService_SendChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatBotServiceServer).SendChat(&chatBotServiceSendChatServer{stream})
}

type ChatBotService_SendChatServer interface {
	Send(*ChatMsgStream) error
	Recv() (*ChatMsgStream, error)
	grpc.ServerStream
}

type chatBotServiceSendChatServer struct {
	grpc.ServerStream
}

func (x *chatBotServiceSendChatServer) Send(m *ChatMsgStream) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatBotServiceSendChatServer) Recv() (*ChatMsgStream, error) {
	m := new(ChatMsgStream)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ChatBotService_RequestChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestChatData)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatBotServiceServer).RequestChat(m, &chatBotServiceRequestChatServer{stream})
}

type ChatBotService_RequestChatServer interface {
	Send(*ChatMsgStream) error
	grpc.ServerStream
}

type chatBotServiceRequestChatServer struct {
	grpc.ServerStream
}

func (x *chatBotServiceRequestChatServer) Send(m *ChatMsgStream) error {
	return x.ServerStream.SendMsg(m)
}

var _ChatBotService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chatbotpb.ChatBotService",
	HandlerType: (*ChatBotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "registerAppService",
			Handler:    _ChatBotService_RegisterAppService_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "sendChat",
			Handler:       _ChatBotService_SendChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "requestChat",
			Handler:       _ChatBotService_RequestChat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chatbot.proto",
}

// ChatBotUserServiceClient is the client API for ChatBotUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatBotUserServiceClient interface {
	// getUserInfo - register app service
	RegisterChatBotServ(ctx context.Context, in *RegisterChatBotServ, opts ...grpc.CallOption) (*ReplyRegisterChatBotServ, error)
}

type chatBotUserServiceClient struct {
	cc *grpc.ClientConn
}

func NewChatBotUserServiceClient(cc *grpc.ClientConn) ChatBotUserServiceClient {
	return &chatBotUserServiceClient{cc}
}

func (c *chatBotUserServiceClient) RegisterChatBotServ(ctx context.Context, in *RegisterChatBotServ, opts ...grpc.CallOption) (*ReplyRegisterChatBotServ, error) {
	out := new(ReplyRegisterChatBotServ)
	err := c.cc.Invoke(ctx, "/chatbotpb.ChatBotUserService/registerChatBotServ", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatBotUserServiceServer is the server API for ChatBotUserService service.
type ChatBotUserServiceServer interface {
	// getUserInfo - register app service
	RegisterChatBotServ(context.Context, *RegisterChatBotServ) (*ReplyRegisterChatBotServ, error)
}

func RegisterChatBotUserServiceServer(s *grpc.Server, srv ChatBotUserServiceServer) {
	s.RegisterService(&_ChatBotUserService_serviceDesc, srv)
}

func _ChatBotUserService_RegisterChatBotServ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterChatBotServ)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatBotUserServiceServer).RegisterChatBotServ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatbotpb.ChatBotUserService/RegisterChatBotServ",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatBotUserServiceServer).RegisterChatBotServ(ctx, req.(*RegisterChatBotServ))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatBotUserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chatbotpb.ChatBotUserService",
	HandlerType: (*ChatBotUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "registerChatBotServ",
			Handler:    _ChatBotUserService_RegisterChatBotServ_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chatbot.proto",
}

func init() { proto.RegisterFile("chatbot.proto", fileDescriptor_chatbot_b4ae99ab1bd86481) }

var fileDescriptor_chatbot_b4ae99ab1bd86481 = []byte{
	// 891 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xcd, 0x6e, 0xe4, 0x44,
	0x10, 0x8e, 0xc7, 0xf3, 0x5b, 0x4e, 0x36, 0x51, 0x27, 0xda, 0xb5, 0x46, 0x10, 0x8d, 0x0c, 0x82,
	0x61, 0x0f, 0x51, 0x34, 0x48, 0xdc, 0x67, 0x93, 0x6c, 0x58, 0x29, 0x61, 0x45, 0x27, 0x1c, 0x90,
	0x10, 0xa8, 0x93, 0xe9, 0xf5, 0x58, 0xcc, 0xd8, 0x4d, 0xbb, 0xbd, 0x52, 0x4e, 0x3c, 0x02, 0x77,
	0x8e, 0xbc, 0x02, 0x8f, 0x80, 0x78, 0x29, 0x4e, 0xa8, 0xca, 0x6e, 0x4f, 0x7b, 0x32, 0x13, 0x7e,
	0x6e, 0x5d, 0x5d, 0xd5, 0x55, 0xdf, 0xf7, 0x55, 0xb9, 0x64, 0xd8, 0xbb, 0x9f, 0x0b, 0x73, 0x97,
	0x99, 0x13, 0xa5, 0x33, 0x93, 0xb1, 0x41, 0x65, 0xaa, 0xbb, 0xe8, 0x4f, 0x0f, 0x82, 0x6f, 0x72,
	0xa9, 0xa7, 0x4a, 0xbd, 0x49, 0xdf, 0x65, 0x6c, 0x0c, 0xbe, 0x50, 0x2a, 0xf4, 0x46, 0xde, 0xf8,
	0xd9, 0xe4, 0xf9, 0x49, 0x1d, 0x78, 0x72, 0x36, 0x17, 0x66, 0xaa, 0xd4, 0xed, 0x83, 0x92, 0x1c,
	0x43, 0xd8, 0x73, 0xe8, 0x0a, 0xa5, 0x8a, 0x64, 0x16, 0xb6, 0x46, 0xde, 0x78, 0xc0, 0x2b, 0x8b,
	0x0d, 0xa1, 0x8f, 0xa7, 0x54, 0x2c, 0x65, 0xe8, 0x93, 0xa7, 0xb6, 0xd1, 0x87, 0x19, 0xd3, 0x62,
	0x99, 0x87, 0xed, 0x91, 0x37, 0xee, 0xf0, 0xda, 0x66, 0x63, 0xd8, 0x2f, 0x72, 0xa9, 0x31, 0x6e,
	0xaa, 0xd4, 0x8d, 0xd4, 0xef, 0xc3, 0x0e, 0x3d, 0x5f, 0xbf, 0x66, 0x0c, 0xda, 0x0b, 0x91, 0xc6,
	0x61, 0x97, 0xdc, 0x74, 0x8e, 0x7e, 0xf3, 0xa0, 0x8f, 0x3c, 0x88, 0xc4, 0x01, 0xf8, 0x88, 0x0b,
	0x49, 0xf8, 0x1c, 0x8f, 0xf8, 0x84, 0x00, 0x95, 0x50, 0xe9, 0xcc, 0x5e, 0x42, 0x5b, 0x28, 0x95,
	0x87, 0xfe, 0xc8, 0x1f, 0x07, 0x0d, 0xae, 0x8e, 0x20, 0x9c, 0x62, 0xf0, 0xbd, 0x11, 0x31, 0x82,
	0xf6, 0xf1, 0x3d, 0x9e, 0x91, 0x0c, 0x96, 0x2e, 0x44, 0x2c, 0x2b, 0xa4, 0xb5, 0xcd, 0x8e, 0xa0,
	0xb3, 0xcc, 0x52, 0xf9, 0x10, 0x02, 0x61, 0x28, 0x8d, 0xe8, 0x57, 0x0f, 0x76, 0xa7, 0x4a, 0x5d,
	0xea, 0xac, 0xf8, 0xaf, 0x6a, 0x6f, 0x50, 0xa7, 0xb5, 0x59, 0x9d, 0x10, 0x7a, 0x31, 0x16, 0x48,
	0x66, 0x95, 0xfc, 0xd6, 0x64, 0x1f, 0xc0, 0x80, 0x8e, 0xa4, 0x44, 0x9b, 0x7c, 0xab, 0x8b, 0xe8,
	0x17, 0x0f, 0x82, 0x2a, 0x07, 0x61, 0x3b, 0x82, 0x8e, 0xc9, 0x7e, 0x94, 0x29, 0xa1, 0x1b, 0xf0,
	0xd2, 0x60, 0xa7, 0xd0, 0x13, 0x25, 0x2e, 0xaa, 0xbf, 0x1d, 0xb5, 0x0d, 0x43, 0x99, 0x2c, 0x44,
	0x3b, 0x0f, 0xd6, 0x46, 0x44, 0xb9, 0xcc, 0xf3, 0x24, 0x4b, 0x93, 0x99, 0x45, 0x54, 0x5f, 0x44,
	0xaf, 0x81, 0x71, 0x19, 0x27, 0xb9, 0xa1, 0x6e, 0x20, 0xb0, 0xe4, 0x5e, 0x56, 0x08, 0x48, 0x01,
	0x44, 0xd6, 0xec, 0x9c, 0x43, 0x80, 0xdb, 0xb0, 0xe8, 0x67, 0x78, 0xc1, 0xa5, 0x5a, 0x3c, 0x6c,
	0x4d, 0x46, 0x74, 0xbc, 0x7f, 0x47, 0xe7, 0x08, 0x3a, 0x52, 0xeb, 0x4c, 0x57, 0xf2, 0x97, 0x86,
	0x43, 0xe4, 0xcd, 0x79, 0xc5, 0x72, 0x75, 0x11, 0x7d, 0x0f, 0xfd, 0xd7, 0xc9, 0x42, 0x9e, 0x0b,
	0x23, 0x50, 0x8e, 0x77, 0xc9, 0x42, 0x92, 0x1c, 0xa5, 0xb2, 0xb5, 0x6d, 0x7d, 0x18, 0x47, 0xe9,
	0x77, 0x79, 0x6d, 0x5b, 0x1f, 0x41, 0xf5, 0x57, 0xef, 0xd0, 0x8e, 0xfe, 0x68, 0x41, 0x0f, 0xc1,
	0x5e, 0xe7, 0x31, 0xce, 0xfe, 0x32, 0x8f, 0xab, 0xd4, 0x78, 0xc4, 0x21, 0x2b, 0x44, 0x42, 0x09,
	0xb7, 0x8f, 0x39, 0x86, 0xb0, 0xcf, 0xc0, 0x17, 0x71, 0x42, 0xe9, 0x83, 0xc9, 0x8b, 0xa6, 0xac,
	0xf5, 0xd0, 0x72, 0x8c, 0x61, 0xc7, 0x0e, 0x0d, 0x6a, 0xdc, 0xab, 0x56, 0xe8, 0x39, 0x54, 0x8e,
	0x1d, 0x2a, 0xf8, 0x71, 0xec, 0xae, 0xfc, 0x44, 0xa7, 0x96, 0xb1, 0xeb, 0xca, 0x58, 0xcf, 0x5c,
	0xcf, 0x9d, 0xb9, 0x86, 0xb8, 0xfd, 0x35, 0x71, 0x6d, 0x25, 0x12, 0x66, 0xd0, 0x44, 0x42, 0x0d,
	0xfb, 0x14, 0xda, 0x78, 0xa6, 0x2f, 0x31, 0x98, 0x1c, 0x3a, 0xac, 0x6c, 0x4f, 0x38, 0x05, 0x44,
	0xbf, 0xb7, 0x60, 0xaf, 0x52, 0xf1, 0xc6, 0x68, 0x29, 0x96, 0x6c, 0x04, 0x81, 0xc9, 0x8c, 0x58,
	0x5c, 0xc9, 0x34, 0x36, 0x73, 0xd2, 0xb4, 0xc3, 0xdd, 0x2b, 0x5a, 0x68, 0x85, 0xbe, 0x31, 0x42,
	0x1b, 0x12, 0x18, 0x17, 0x5a, 0x65, 0x23, 0xec, 0xfb, 0x42, 0x57, 0x6f, 0x7d, 0x72, 0xae, 0x2e,
	0xf0, 0xe5, 0x5c, 0xe4, 0x73, 0x12, 0xa8, 0x9c, 0xfc, 0xda, 0x66, 0x1f, 0xc3, 0x1e, 0x15, 0xf9,
	0xd2, 0x06, 0x94, 0xeb, 0xa5, 0x79, 0x89, 0x3b, 0x69, 0x86, 0xce, 0x2e, 0x4d, 0x0a, 0x9d, 0x57,
	0xb2, 0xf6, 0x36, 0xca, 0xda, 0xdf, 0x2a, 0xeb, 0x60, 0x5d, 0xd6, 0x4f, 0xa0, 0x8d, 0x4a, 0x55,
	0xb2, 0xb1, 0xb5, 0xcf, 0xe2, 0x3a, 0x8f, 0x39, 0xf9, 0xa3, 0x0b, 0xd8, 0xe7, 0xf2, 0xa7, 0x42,
	0xe6, 0x06, 0xef, 0x6d, 0x6f, 0x37, 0x6c, 0x8e, 0x46, 0xb9, 0xd6, 0xfa, 0x27, 0x22, 0x60, 0x1f,
	0xdf, 0xbf, 0xca, 0xcc, 0x3f, 0x2c, 0xa0, 0x27, 0xd3, 0xa0, 0xaa, 0xb9, 0xd4, 0xef, 0xbf, 0x72,
	0x96, 0x8d, 0xb5, 0xa3, 0x6b, 0x38, 0xb4, 0x1b, 0xc0, 0x29, 0xc5, 0xbe, 0x28, 0x9f, 0x60, 0xc9,
	0x6a, 0xa1, 0x0c, 0xd7, 0xc8, 0x3a, 0xa0, 0x78, 0x1d, 0x1b, 0xcd, 0x20, 0x6c, 0x6c, 0x15, 0x37,
	0xe7, 0xff, 0x81, 0x5e, 0xb7, 0xce, 0x77, 0x5a, 0xf7, 0xf2, 0x04, 0x02, 0x67, 0x0d, 0xb1, 0x03,
	0xd8, 0x3d, 0x9b, 0xde, 0xfe, 0x70, 0x7b, 0x71, 0x75, 0x71, 0xc9, 0xa7, 0xd7, 0x07, 0x3b, 0x6c,
	0x0f, 0x06, 0x78, 0x73, 0xf6, 0xf6, 0xed, 0xd5, 0xd7, 0x07, 0xde, 0xe4, 0x2f, 0x0f, 0x9e, 0x39,
	0x48, 0x70, 0xc7, 0x7d, 0x0b, 0x4c, 0x3f, 0xde, 0x7c, 0x1f, 0x3a, 0x24, 0x1f, 0x2f, 0xc6, 0x61,
	0xd4, 0x70, 0x6f, 0x5c, 0x9e, 0xd1, 0x0e, 0x3b, 0x47, 0xed, 0xd2, 0x19, 0x16, 0x64, 0xe1, 0xe3,
	0x11, 0x29, 0x3f, 0xa3, 0xe1, 0x56, 0x4f, 0xb4, 0x33, 0xf6, 0x4e, 0x3d, 0x76, 0x09, 0x81, 0x5e,
	0x8d, 0x10, 0x1b, 0x36, 0x4a, 0x37, 0x46, 0xeb, 0xa9, 0x54, 0xa7, 0xde, 0x44, 0x03, 0xab, 0xb8,
	0xe3, 0x6a, 0xb3, 0x4c, 0xbf, 0x83, 0x43, 0xbd, 0xa1, 0x47, 0xc7, 0x1b, 0x04, 0x70, 0xfc, 0xc3,
	0x8f, 0xb6, 0x29, 0xe0, 0x04, 0x45, 0x3b, 0x77, 0x5d, 0xfa, 0xa5, 0xfa, 0xfc, 0xef, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x3d, 0x46, 0xe9, 0xeb, 0x63, 0x09, 0x00, 0x00,
}
